name: "Build Docker image"
on:
  push:
    branches:
      - main
    tags:
      - "*.*.*"
      - "v*.*.*"
      - "*.*.*-*"
      - "v*.*.*-*"
    paths:
      - ".github/workflows/docker.yaml"
      - "Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: "--debug"
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.REPOSITORY_USER }}
          password: ${{ secrets.REPOSITORY_TOKEN }}
      - name: extra tags
        if: startsWith( github.ref, 'refs/tags/')
        run: |
          tag_name=`echo $GITHUB_REF | sed -e 's:^refs/tags/::'`
          EXTRA_OPTS="-t rinx/alpine-fennel:${tag_name} -t ghcr.io/rinx/alpine-fennel:${tag_name}"
          echo "EXTRA_OPTS=${EXTRA_OPTS}" >> $GITHUB_ENV
      - name: Build
        run: |
          docker buildx build \
            --platform ${PLATFORMS} \
            --builder ${BUILDER} \
            --label org.opencontainers.image.url=${{ github.event.repository.html_url }} \
            --label org.opencontainers.image.source=${{ github.event.repository.html_url }} \
            --label org.opencontainers.image.revision=${{ github.sha }} \
            --push \
            ${EXTRA_OPTS} \
            -t rinx/alpine-fennel:latest \
            -t ghcr.io/rinx/alpine-fennel:latest \
            .
        env:
          DOCKER_BUILDKIT: 1
          PLATFORMS: "linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x"
          BUILDER: ${{ steps.buildx.outputs.name }}
